### ISSUE TITLE
Make useHostNameAsBookieID configurable

### ISSUE THREAD

**Issue by RaulGracia** [pravega/bookkeeper-operator#112]
### Description

At the moment, `useHostNameAsBookieID` is hardcoded, which limits the configuration of Bookies. We need this flag to be configurable, as it may have important implications on a Bookkeeper deployment.

### Importance

This can be classified as "must-have".

### Location

Bookkeeper configuration.

### Suggestions for an improvement

Allow user input to change `useHostNameAsBookieID`.

**Comment by SrishT** [comment]
Closing this issue since even at present the value of the option `useHostNameAsBookieID` which is set to `true` by the operator code, can be overridden by the user.
