### ISSUE TITLE
Allow extra volume mounts to be configured

### ISSUE THREAD

**Issue by leapsky** [pravega/bookkeeper-operator#115]
### Description

Bookkeeper operator should allow to specify "extra" volumes to be mounted into a bookie container.

### Importance

This functionality is needed to share directories between the hosts and containers, store logs and crash dumps.

### Location

`pkg/controller/bookkeepercluster/bookie.go`

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/bookkeeper-operator/pull/116
