### ISSUE TITLE
Certificate issue with Bookkeeper Operator Installation

### ISSUE THREAD

**Issue by dellThejas** [pravega/bookkeeper-operator#167]
### Description

Certificates have been deployed, but upon starting Bookkeeper Operator installation using helm, it complains that it cannot connect to the webhook cert.

### Importance

should-have

### Location

I executed the following commands:

$ kubectl create -f deploy/certificate.yaml
$ helm repo add pravega https://charts.pravega.io
$ helm repo update
$ helm install pravega/bookkeeper-operator 

Here is the condition of the Bookkeeper Operator pod
![image](https://user-images.githubusercontent.com/55413736/132369861-c1535dd7-9be8-4eed-983f-eb1cca32ac9b.png)

**Comment by anishakj** [comment]
@dellThejas  Have you installed cert-manager as well, it is a pre-requisite?

**Comment by dellThejas** [comment]
Fixed this by installing certmanager.
