### ISSUE TITLE
Please release new version to support PodDisruptionBudget policy/v1

### ISSUE THREAD

**Issue by junglie85** [pravega/bookkeeper-operator#230]
Please can you release an updated version of the operator and Helm chart?

https://github.com/pravega/bookkeeper-operator/commit/24f6cd1d592409406589a5a9fa3a49dbd093aeed updates the operator for the  `PodDisruptionBudget` API to `policy/v1` but there has been no release meaning we cannot use it on newer clusters.

Currently, I get the following error when trying to deploy to a 1.26 cluster:

```
{"level":"error","ts":1683885052.0189013,"logger":"controller.bookkeepercluster","msg":"Reconciler error","reconciler group":"bookkeeper.pravega.io","reconciler kind":"BookkeeperCluster","name":"bookkeeper","namespace":"pravega","error":"failed to reconcile pdb no matches for kind \"PodDisruptionBudget\" in version \"policy/v1beta1\"","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:266\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.0/pkg/internal/controller/controller.go:227"}
```

**Comment by junglie85** [comment]
The CRD's in the currently released Helm chart are also out of date - see #231.

**Comment by RaulGracia** [comment]
@anishakj this is breaking the deployment for Bookkeeper, please find some time to work on this. Thanks!

**Comment by anishakj** [comment]
New version of bookkeeper-operator is released https://github.com/pravega/charts/releases/tag/bookkeeper-operator-0.2.4
