### ISSUE TITLE
Deletion of LongTermStorage to be handled by bookkeeper-operator

### ISSUE THREAD

**Issue by Prabhaker24** [pravega/bookkeeper-operator#31]
### Description
LongTermStorage's deletion is required as part of a redeployment of bk-cluster( that is once the pravega cluster and bk-cluster are deployed and we undeploy them and when we redeploy them) in that case for the i/o to work. this is needed as otherwise, the controller will point to the wrong metadata entries and because of which i/o will fail with a 503 error...additionally in case the user doesn't want to remove his LongTermStorage what he can do is while redeploying he can deploy using a different LongTermStorage and in case he is using the same LongTermStorage bk-operator should give the necessary warnings.  

### Importance
nice to have 

### Location
while deleting the bookkeeper cluster bk-operator should delete the LongTermStorage and in case the user wants don't want to delete LongTermStorage bk-operator  should give warning to the user to use another pvc as using the same  LongTermStorage  will cause issues this can be done in the **bookkeepercluster_controller.go** 

### Suggestions for an improvement
In the bookkeepercluster_controller.go while we are removing the zk metadata we can additionally remove the LongTermStorage as well.

**Comment by pbelgundi** [comment]
@Prabhaker24 please move to Pravega Operator issue queue

**Comment by Prabhaker24** [comment]
I am seeing a similar issue on pravega operator link to it is https://github.com/pravega/pravega-operator/issues/370, so I am closing this one
