### ISSUE TITLE
Allow ingestion of user defined env vars in Bookie containers

### ISSUE THREAD

**Issue by pbelgundi** [pravega/bookkeeper-operator#5]
### Description

User should be able to create a config map with K:Vs and provide the name of the same in the manifest. Operator should plug this config map into the bookie pods so the variables defined there-in are available inside Bookie containers

### Importance

must-have

**Comment by bourgeoisor** [comment]
I can't add labels but note @pbelgundi / @SrishT that this is a blocker issue.

**Comment by pbelgundi** [comment]
These 2 environment variables need to be removed from the operator config map ( as they are Pravega specific):
```
PRAVEGA_CLUSTER_NAME
WAIT_FOR
```
These should be added by the user config map instead.
