### ISSUE TITLE
Bookkeeper chart does not expose logging configs.

### ISSUE THREAD

**Issue by realAaronWu** [pravega/bookkeeper-operator#83]
### Description

Bookkeeper chart currently does not allow users to set bookkeeper logging configs such as levels and logging file appenders, etc. 

### Importance

must-have

### Location
charts/bookkeeper

### Suggestions for an improvement
expose chart settings like bookkeeper.logging.level and bookkeeper.logging.appender to set logging behaviour of bookkeeper.

**Comment by anishakj** [comment]
Fixed by PR https://github.com/pravega/bookkeeper-operator/issues/83
