### ISSUE TITLE
Invalid JVM Options for JDK 11 (Bookkeeper +4.11)

### ISSUE THREAD

**Issue by RaulGracia** [pravega/bookkeeper-operator#92]
### Description

Bookkeeper operator does not work with Bookkeeper 4.11.x. The reason is that Bookkeeper 4.11.x switched to JDK 11 and some of the JVM options used in the Bookkeeper Operator (i.e., https://github.com/pravega/bookkeeper-operator/blob/8af58c5faf510b6fbd1287679c60ab971a9f7912/pkg/controller/bookkeepercluster/bookie.go#L302) are invalid for JDK 11.

### Importance

Must-have.

### Location

JVM Options of Bookkeeper.

### Suggestions for an improvement

Either add `-XX:+IgnoreUnrecognizedVMOptions` as a JVM option or adapt the JVM options depending on the Bookkeeper version being deployed.

**Comment by fonfrygin** [comment]
By what time can we expect this problem to be fixed?

**Comment by RaulGracia** [comment]
@fonfrygin this will be probably fixed in the next version of Helm Charts, if I'm not mistaken. Meanwhile, you could just add `-XX:+IgnoreUnrecognizedVMOptions` to the chart/manifest JVM options and it should work. cc/ @SrishT @anishakj
